name: oopc-nlp
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - freetype=2.10.2
  - intel-openmp=2020.1
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ninja=1.9.0
  - numpy-base=1.18.5
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.1.2
  - pip=20.1.1
  - python=3.8.3
  - pytorch=1.5.1
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - torchvision=0.6.1
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - attrs==19.3.0
    - chardet==3.0.4
    - click==7.1.2
    - filelock==3.0.12
    - flask==1.1.2
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - joblib==0.16.0
    - markupsafe==1.1.1
    - multidict==4.7.6
    - numpy==1.19.0
    - packaging==20.4
    - pyparsing==2.4.7
    - regex==2020.6.8
    - requests==2.24.0
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - slackclient==2.7.2
    - tokenizers==0.8.0rc4
    - tqdm==4.47.0
    - transformers==3.0.1
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - yarl==1.4.2
#prefix: C:\Users\nacharya\Anaconda3\envs\nlp-pipeline

